<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
            schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>g1_policy_controller</name>
  <version>0.1.0</version>
  <description>
    ROS 2 controller for the 12-DoF Unitree G1 locomotion policy in Isaac Sim.
  </description>
  <maintainer email="khoa-ng@example.com">khoa-ng</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ament_cmake_python</depend>
  <depend>ament_index_python</depend>
  <depend>geometry_msgs</depend>
  <depend>message_filters</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>

  <test_depend>ament_cmake_test</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
